# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ebc401fe2cda1c454dd1b314c5883c3d1b9da6b20bd0313e6d8be73533109b2b6c799dc2ecb815a292b8dcfaca317b5983ae98f63dc0db59f9f9c731cae48e

test:
  secret_key_base: a87cd9c16cf680468656676e7e218c7c7d603bb27d0a5bc2c984da98f30ad526262b901295b4dc30a17403059f315b69a801e4a3a9a6e0c9f13a052a570cd0bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
